version: "3.9"
   
services:
  converter:
    build: .
    command: python ./src/main.py
    environment:
      - TZ=Europe/Berlin
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "3"
    network_mode: host
    volumes:
      - type: bind
        source: ./data
        target: /usr/src/app/data