name: Convert collection to SKOS

on: push

jobs:
  convert-collection-to-skos:
    name: Convert edu-sharing collections to SKOS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: make data folder
        runs: mkdir data

      - name: run conversion
        run: python3 auto-convert-collection-to-skos

      - name: make public folder
        runs: mkdir public

      - name: make .env.production file
        run: echo "PATH_PREFIX=/convert-collection-to-skos" > .env.production

      - name: build public dir with docker image
        run: docker run -v $(pwd)/public:/app/public -v $(pwd)/data:/app/data -v $(pwd)/.env.production:/app/.env.production skohub/skohub-vocabs-docker:latest

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public